[build]
  command = "npx ng build --configuration production"
    publish = "dist/bharat-ghumho/browser"

    [[plugins]]
      package = "@netlify/plugin-angular"
        [plugins.inputs]
            disable = true
